#!/usr/bin/env bash

# set -o xtrace

AUTOLOAD=${$HOME}/.vim/autoload
BUNDLE=${HOME}/.vim/bundle

pathogen() {
  curl -Sso ${AUTOLOAD}/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
}

clone() {
  local repos=(
    https://github.com/altercation/vim-colors-solarized.git
    https://github.com/benmills/vimux.git
    https://github.com/elixir-lang/vim-elixir.git
    https://github.com/ervandew/supertab.git
    https://github.com/kelan/gyp.vim.git
    https://github.com/markcornick/vim-vagrant.git
    https://github.com/michaelnisi/swift.vim.git
    https://github.com/michaelnisi/vim-erlang-skeletons.git
    https://github.com/oscarh/vimerl.git
    https://github.com/vim-scripts/dtrace-syntax-file.git
    https://github.com/vim-scripts/jade.vim.git
    https://github.com/vim-scripts/nginx.vim.git
    https://github.com/wincent/Command-T.git
  )
  mkdir -p $AUTOLOAD $BUNDLE
  cd $BUNDLE || exit 1
  for repo in "${repos[@]}"
  do
    git clone "$repo"
  done
}

echo "Downloading Pathogen"
pathogen

echo "Cloning"
clone

exit
